services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bun-api
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: bun run --watch src/index.ts
    environment:
      CORS_ALLOWED_ORIGINS: '["http://localhost:3000"]'
