services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bun-api
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: bun run --watch src/index.ts